version: "3.9"

services:
  web:
    build: ./web
    container_name: flask
    ports:
      - "8000:5000"
    # environment:
    #   FLASK_ENV: development
    #   FLASK_APP: web.app:app
    

  mysql:
    image: mysql:8.0.28
    platform: linux/amd64
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      TZ: "Asia/Tokyo"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql



# version: "3.9"

# services:
#   web:
#     build: ./web
#     container_name: flask
#     ports:
#       - "8000:5000"

#   mysql:
#     image: mysql:8.0.28
#     platform: linux/amd64
#     container_name: mysql-container
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: demo
#       TZ: "Asia/Tokyo"
#     volumes:
#       - ./my.cnf:/etc/mysql/conf.d/my.cnf